apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lgtm.fullname" . }}
  labels:
    {{- include "lgtm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "lgtm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "lgtm.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            {{- if not (eq .Values.gitlab.address "") }}
            - name: GITLAB_ADDR
              value: {{ .Values.gitlab.address | quote }}
            {{- end }}
            - name: GITLAB_GROUP
              value: {{ .Values.gitlab.groupName | quote }}
            - name: GITLAB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.gitlab.tokenSecret.name | quote }}
                  key: {{ .Values.gitlab.tokenSecret.key | quote }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
